export const MEDICINE_MANAGE_ROLES = ['ADMIN', 'PHARMACY_MANAGER', 'INVENTORY_MANAGER'] as const
export const PURCHASE_MANAGE_ROLES = ['ADMIN', 'PHARMACY_MANAGER', 'INVENTORY_MANAGER'] as const
export const SALE_MANAGE_ROLES = ['ADMIN', 'PHARMACY_MANAGER', 'SALES_CLERK'] as const
export const INVENTORY_VIEW_ROLES = ['ADMIN', 'PHARMACY_MANAGER', 'INVENTORY_MANAGER'] as const
export const WARNING_MANAGE_ROLES = ['ADMIN', 'PHARMACY_MANAGER', 'INVENTORY_MANAGER'] as const
export const CONTROLLED_VIEW_ROLES = ['ADMIN', 'PHARMACY_MANAGER', 'INVENTORY_MANAGER'] as const
export const USER_MANAGE_ROLES = ['ADMIN'] as const
export const LOG_VIEW_ROLES = ['ADMIN', 'PHARMACY_MANAGER'] as const
